### ISSUE TITLE
查看子应用，多层嵌套用不同颜色展示

### ISSUE THREAD

**Issue by raoenhui** [micro-zoe/micro-app-chrome-plugin#15]
## 背景
> 描述您希望改进的问题。

**Comment by ChenBu2** [comment]
['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'] 增加几种颜色，按照角标顺序获取

**Comment by ChenBu2** [comment]
<img width="1787" alt="image" src="https://github.com/micro-zoe/micro-app-chrome-plugin/assets/15308674/9e999542-e8f9-42ed-ac1a-19b133ff25fc">

**Comment by raoenhui** [comment]
https://github.com/micro-zoe/micro-app-chrome-plugin/pull/31/files
