### ISSUE TITLE
内网安装报错

### ISSUE THREAD

**Issue by littlewhiteprogrammer** [micro-zoe/micro-app-chrome-plugin#18]
加载扩展程序出错
无法加载已下来源的扩展程序： C:
\Users\DS_SON~1\AppData\Local\Temp\Micro-app-chrome-plugin_7108_507471535.Permission‘devtools’ cannot be spectified in the manifest

**Comment by zhouran19880120** [comment]
可能您的Chrome安全设置过严导致，使得插件无法在开发者工具Console面板里创建页签。
您可尝试在Chrome设置页面的“隐私和安全”页面适当放宽限制。为进一步排查问题，请提供Chrome版本号、相关截图供我们排查谢谢！

**Comment by littlewhiteprogrammer** [comment]
![WechatIMG145](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/24727089/0325f4eb-5df8-4696-aa8d-8797a537e8cc)
![WechatIMG146](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/24727089/120321b8-68ef-4fdb-8f7a-7542b6fd23ee)

**Comment by littlewhiteprogrammer** [comment]
chrome 版本  105.0.5195.127(正式版本) （64位）

**Comment by zhouran19880120** [comment]
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/20079220/715cb27e-8924-4df1-91b6-3df6e2041dca)
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/20079220/e63b1a1e-7ee1-4c01-afeb-d07a3c59aa95)

**Comment by zhouran19880120** [comment]
由于Chrome105.0.5195.127版本过老，导致插件manifest.json文件里的permissions.devtools无法识别。建议您升级Chrome浏览器使用，感谢！

**Comment by raoenhui** [comment]
inactive
