### ISSUE TITLE
动态获取变量

### ISSUE THREAD

**Issue by raoenhui** [micro-zoe/micro-app-chrome-plugin#2]
## 背景
> 描述您希望改进的问题
目前所有版本都展示相同环境变量

## 期望的效果
不同版本展示全局变量

**Comment by zhouran19880120** [comment]
通过遍历window对象，找出__MICRO_APP开头的变量来展示

**Comment by zhouran19880120** [comment]
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/20079220/460abb3d-0fb1-47be-8824-50b23c90e092)
