### ISSUE TITLE
新增嵌套环境下的父子应用通信

### ISSUE THREAD

**Issue by raoenhui** [micro-zoe/micro-app-chrome-plugin#37]
## 背景
> 可用microApp.getData('my-app')

**Comment by raoenhui** [comment]
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/14011130/2728568b-b400-4001-8b8f-1b8e54c4b159)

**Comment by zhouran19880120** [comment]
已支持嵌套应用

**Comment by raoenhui** [comment]
https://github.com/micro-zoe/micro-app-chrome-plugin/pull/36
