### ISSUE TITLE
全局变量：备注从自己数据字点链接到官网

### ISSUE THREAD

**Issue by raoenhui** [micro-zoe/micro-app-chrome-plugin#4]
## 背景
> 描述您希望改进的问题。

## 期望的效果
全局变量：备注从自己数据字点链接到官网

**Comment by zhouran19880120** [comment]
本地保存一个对应列表，根据全局变量来查找相应的url，支持点击打开

**Comment by raoenhui** [comment]
https://github.com/micro-zoe/micro-app-chrome-plugin/pull/22

**Comment by zhouran19880120** [comment]
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/20079220/049f2905-66ce-4d8b-9c5e-90cb69c6df75)

**Comment by raoenhui** [comment]
测试@ChenBu2
