### ISSUE TITLE
https://zeroing.jd.com/micro-app/ 同步github.io

### ISSUE THREAD

**Issue by raoenhui** [micro-zoe/micro-app-chrome-plugin#40]
## 背景
> 描述您希望改进的问题。

## 期望的效果
nginx转发过去

**Comment by zhouran19880120** [comment]
仅保留示例文件通过zeroing域名访问，其余都转发到Github域名上。
Nginx配置识别路由，当路由为/micro-app/demo、/micro-app/react16、/micro-app/react17、/micro-app/vue2、/micro-app/vue3、/micro-app/vite、/micro-app/angular11时依旧保持原样，其余都return 301 https://micro-zoe.github.io/micro-app/
