### ISSUE TITLE
 安装即报错

### ISSUE THREAD

**Issue by dean5277** [micro-zoe/micro-app-chrome-plugin#47]
## 问题描述
> 安装即报错

## 复现步骤
![image](https://github.com/micro-zoe/micro-app-chrome-plugin/assets/1802631/85a0c29e-7307-48e3-89a2-12f905f8e5a2)

## 上传截图
> 请上传代码截图、控制台、终端等截图以帮助我们了解您的问题。

## 复现仓库
> 请提供一个精简的代码仓库，然后上传到自己的 github，以帮助我们复现您的问题。

## 环境信息
版本 120.0.6099.200（正式版本） （64 位）

**Comment by raoenhui** [comment]
这块报错不影响正常使用哈
